/* GENERATED by scripts/build.js from content/ — do not edit by hand.
   To add or change a project, edit content/<slug>/ then run the build (or Publish.command). */
window.KODU_PROJECTS = {
  "courtside-wines": {
    "name": "Courtside Wines",
    "info": "Branding, Print & Web",
    "images": [
      {
        "src": "images/courtside-wines/tote",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-10",
        "alt": "Courtside Wines: Tote"
      },
      {
        "src": "images/courtside-wines/vineyard-graphic",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-9",
        "alt": "Courtside Wines: Vineyard Graphic"
      },
      {
        "src": "images/courtside-wines/tshirt-front",
        "widths": [
          1200,
          2000,
          2309
        ],
        "ratio": "portrait",
        "alt": "Courtside Wines: Tshirt Front"
      },
      {
        "src": "images/courtside-wines/tshirt-back",
        "widths": [
          1200,
          2000,
          2309
        ],
        "ratio": "portrait",
        "alt": "Courtside Wines: Tshirt Back"
      },
      {
        "src": "images/courtside-wines/business-card",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-9",
        "alt": "Courtside Wines: Business Card"
      },
      {
        "src": "images/courtside-wines/poster-01",
        "widths": [
          1188
        ],
        "ratio": "poster",
        "alt": "Courtside Wines: Poster 01"
      },
      {
        "src": "images/courtside-wines/poster-02",
        "widths": [
          1188
        ],
        "ratio": "poster",
        "alt": "Courtside Wines: Poster 02"
      },
      {
        "src": "images/courtside-wines/poster-03",
        "widths": [
          1188
        ],
        "ratio": "poster",
        "alt": "Courtside Wines: Poster 03"
      },
      {
        "src": "images/courtside-wines/multi-mag",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-10",
        "alt": "Courtside Wines: Multi Mag"
      },
      {
        "src": "images/courtside-wines/macbook-01",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-10",
        "alt": "Courtside Wines: Macbook 01"
      },
      {
        "src": "images/courtside-wines/macbook-02",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-10",
        "alt": "Courtside Wines: Macbook 02"
      }
    ]
  },
  "grampians-sandstone": {
    "name": "Grampians Sandstone",
    "info": "Website Design & Build",
    "images": [
      {
        "src": "images/grampians-sandstone/laptop-hero",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-10",
        "alt": "Grampians Sandstone: Laptop Hero"
      },
      {
        "src": "images/grampians-sandstone/homepage-screen",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-10",
        "alt": "Grampians Sandstone: Homepage Screen"
      },
      {
        "src": "images/grampians-sandstone/text-overlay",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-10",
        "alt": "Grampians Sandstone: Text Overlay"
      },
      {
        "src": "images/grampians-sandstone/photo-building",
        "widths": [
          1200,
          1500
        ],
        "ratio": "portrait",
        "alt": "Grampians Sandstone: Photo Building"
      },
      {
        "src": "images/grampians-sandstone/photo-clocktower",
        "widths": [
          1200,
          1500
        ],
        "ratio": "portrait",
        "alt": "Grampians Sandstone: Photo Clocktower"
      },
      {
        "src": "images/grampians-sandstone/product-slider",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-10",
        "alt": "Grampians Sandstone: Product Slider"
      },
      {
        "src": "images/grampians-sandstone/image-slider",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-9",
        "alt": "Grampians Sandstone: Image Slider"
      },
      {
        "src": "images/grampians-sandstone/page-specifications",
        "widths": [
          1200,
          2000,
          2400
        ],
        "ratio": "third",
        "alt": "Grampians Sandstone: Page Specifications"
      },
      {
        "src": "images/grampians-sandstone/page-frame-2",
        "widths": [
          1200,
          2000,
          2400
        ],
        "ratio": "third",
        "alt": "Grampians Sandstone: Page Frame 2"
      },
      {
        "src": "images/grampians-sandstone/page-frame-3",
        "widths": [
          1200,
          2000,
          2400
        ],
        "ratio": "third",
        "alt": "Grampians Sandstone: Page Frame 3"
      },
      {
        "src": "images/grampians-sandstone/digger",
        "widths": [
          1200,
          2000,
          2440
        ],
        "ratio": "16-10",
        "alt": "Grampians Sandstone: Digger"
      },
      {
        "src": "images/grampians-sandstone/mobile-overlay",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-9",
        "alt": "Grampians Sandstone: Mobile Overlay"
      }
    ]
  },
  "alpha-life-essentials": {
    "name": "Alpha Life Essentials",
    "info": "Video platform for connection",
    "images": [
      {
        "src": "images/alpha-life-essentials/floatingphones",
        "widths": [
          1200,
          2000,
          2800
        ],
        "ratio": "16-10",
        "alt": "Alpha Life Essentials: Floatingphones"
      }
    ]
  }
};
