/* GENERATED by scripts/build.js from content/ — do not edit by hand.
   To add or change a project, edit content/<slug>/ then run the build (or Publish.command). */
window.KODU_PROJECTS = {
  "nsw-mining": {
    "name": "NSW Mining Careers",
    "info": "Choose Your Adventure",
    "overview": "A careers site for NSW Mining built to help people find their way into the industry. Alongside the full site system, I designed an interactive questionnaire that matches visitors with the mining careers that suit them, then points them to the pathways to get there.",
    "role": [
      "Site System Design",
      "UI Design",
      "User Experience",
      "Careers Questionnaire Design",
      "Figma Prototype"
    ],
    "roleLabel": "",
    "team": [
      "BEECH Agency team"
    ],
    "link": "https://nswminingcareers.com.au/",
    "linkLabel": "",
    "images": [
      {
        "src": "images/nsw-mining/01-careers-site-feature",
        "widths": [
          1200,
          2000,
          2880
        ],
        "cols": 1,
        "aspect": "16 / 9",
        "alt": "NSW Mining Careers: Careers Site Feature"
      },
      {
        "src": "images/nsw-mining/02-job-selector",
        "widths": [
          1200,
          2440
        ],
        "cols": 1,
        "aspect": "16 / 9",
        "alt": "NSW Mining Careers: Job Selector"
      },
      {
        "src": "images/nsw-mining/03-location-slider",
        "widths": [
          1200,
          2440
        ],
        "cols": 1,
        "aspect": "16 / 10",
        "alt": "NSW Mining Careers: Location Slider"
      },
      {
        "src": "images/nsw-mining/04-careers-guide",
        "widths": [
          1200,
          2880
        ],
        "cols": 1,
        "aspect": "16 / 10",
        "alt": "NSW Mining Careers: Careers Guide"
      },
      {
        "src": "images/nsw-mining/05-careers-phone",
        "widths": [
          1200,
          2600
        ],
        "cols": 1,
        "aspect": "16 / 9",
        "alt": "NSW Mining Careers: Careers Phone"
      },
      {
        "src": "images/nsw-mining/06-mining-page-tall-a",
        "widths": [
          1760
        ],
        "cols": 2,
        "aspect": "1760 / 3513",
        "tall": true,
        "alt": "NSW Mining Careers: Mining Page Tall A"
      },
      {
        "src": "images/nsw-mining/07-mining-page-tall-b",
        "widths": [
          1760
        ],
        "cols": 2,
        "aspect": "1760 / 3141",
        "tall": true,
        "alt": "NSW Mining Careers: Mining Page Tall B"
      },
      {
        "src": "images/nsw-mining/08-find-a-career-mobile",
        "widths": [
          1200,
          2600
        ],
        "cols": 1,
        "aspect": "16 / 9",
        "alt": "NSW Mining Careers: Find A Career Mobile"
      }
    ]
  },
  "alpha-life-essentials": {
    "name": "Alpha Life Essentials",
    "info": "Video platform for connection",
    "overview": "A watch party video platform for curious young people with big questions, built for Life Essentials, a series by Alpha. The brief was a full video platform that feels as intuitive as Netflix: users can sign up, create and join multiple watch parties, edit their profile and download resources along the way.",
    "role": [
      "User Experience",
      "UI Design",
      "Site System Design",
      "Portal Login Flow",
      "Figma Prototype"
    ],
    "roleLabel": "",
    "team": [
      "BEECH Agency team",
      "Josh Wayman & Dom Andrews (Development)"
    ],
    "link": "https://app.lifeessentials.com.au/",
    "linkLabel": "",
    "images": [
      {
        "src": "images/alpha-life-essentials/01-alphafloatingphones",
        "widths": [
          1200,
          2000,
          3000
        ],
        "cols": 1,
        "aspect": "16 / 10",
        "alt": "Alpha Life Essentials: Alphafloatingphones"
      },
      {
        "src": "images/alpha-life-essentials/02-website-layout",
        "widths": [
          1800
        ],
        "cols": 2,
        "aspect": "1800 / 2520",
        "alt": "Alpha Life Essentials: Website Layout"
      },
      {
        "src": "images/alpha-life-essentials/03-website-layout",
        "widths": [
          1800
        ],
        "cols": 2,
        "aspect": "1800 / 2520",
        "alt": "Alpha Life Essentials: Website Layout"
      },
      {
        "src": "images/alpha-life-essentials/04-multisignup",
        "widths": [
          1200,
          3000
        ],
        "cols": 1,
        "aspect": "16 / 9",
        "alt": "Alpha Life Essentials: Multisignup"
      },
      {
        "src": "images/alpha-life-essentials/05-alphamutliprofile",
        "widths": [
          1200,
          3000
        ],
        "cols": 1,
        "aspect": "16 / 9",
        "alt": "Alpha Life Essentials: Alphamutliprofile"
      }
    ]
  },
  "aqua-club": {
    "name": "Aqua Club",
    "info": "Branding for Yacht Toys",
    "overview": "Brand identity for Aqua Club, Australian premium yacht toys, run by a good mate of mine, Tyler. A personal project covering the logo, a simple identity system and how the mark sits on the products themselves, so it reads just as well out on the water as it does on screen.",
    "role": [
      "Logo Design",
      "Brand Identity",
      "Product Logo Placement"
    ],
    "roleLabel": "",
    "team": [],
    "link": "https://www.aquaclub.com.au/",
    "linkLabel": "Check them out",
    "images": [
      {
        "src": "images/aqua-club/01-jetskidock",
        "widths": [
          1200,
          3000
        ],
        "cols": 1,
        "aspect": "16 / 9",
        "alt": "Aqua Club: Jetskidock"
      },
      {
        "src": "images/aqua-club/02-jetskidock",
        "widths": [
          1067
        ],
        "cols": 2,
        "aspect": "4 / 5",
        "alt": "Aqua Club: Jetskidock"
      },
      {
        "src": "images/aqua-club/03-logoonwater",
        "widths": [
          1200,
          2112
        ],
        "cols": 2,
        "aspect": "4 / 5",
        "alt": "Aqua Club: Logoonwater"
      },
      {
        "src": "images/aqua-club/04-toybehindeboat",
        "widths": [
          1200,
          3000
        ],
        "cols": 1,
        "aspect": "16 / 9",
        "alt": "Aqua Club: Toybehindeboat"
      }
    ]
  },
  "grampians-sandstone": {
    "name": "Grampians Sandstone",
    "info": "Website Design & Build",
    "overview": "A full website design and build for Grampians Sandstone, a supplier of natural Victorian sandstone. The site pairs large-scale photography with a clear product structure, so architects, landscapers and homeowners can quickly find the right stone for their project.",
    "role": [
      "Visual Design System",
      "User Experience",
      "WordPress Block System",
      "Figma Prototype"
    ],
    "roleLabel": "",
    "team": [
      "BEECH Agency team"
    ],
    "link": "https://grampianssandstone.com.au",
    "linkLabel": "",
    "images": [
      {
        "src": "images/grampians-sandstone/01-laptop-hero",
        "widths": [
          1200,
          2880
        ],
        "cols": 1,
        "aspect": "16 / 10",
        "alt": "Grampians Sandstone: Laptop Hero"
      },
      {
        "src": "images/grampians-sandstone/02-homepage-screen",
        "widths": [
          1200,
          2000,
          2800
        ],
        "cols": 1,
        "aspect": "16 / 10",
        "alt": "Grampians Sandstone: Homepage Screen"
      },
      {
        "src": "images/grampians-sandstone/03-text-overlay",
        "widths": [
          1200,
          2000,
          2800
        ],
        "cols": 1,
        "aspect": "16 / 10",
        "alt": "Grampians Sandstone: Text Overlay"
      },
      {
        "src": "images/grampians-sandstone/04-photo-building",
        "widths": [
          1500
        ],
        "cols": 2,
        "aspect": "1500 / 1875",
        "alt": "Grampians Sandstone: Photo Building"
      },
      {
        "src": "images/grampians-sandstone/05-photo-clocktower",
        "widths": [
          1500
        ],
        "cols": 2,
        "aspect": "1500 / 1875",
        "alt": "Grampians Sandstone: Photo Clocktower"
      },
      {
        "src": "images/grampians-sandstone/06-product-slider",
        "widths": [
          1200,
          2000,
          2800
        ],
        "cols": 1,
        "aspect": "16 / 10",
        "alt": "Grampians Sandstone: Product Slider"
      },
      {
        "src": "images/grampians-sandstone/07-image-slider",
        "widths": [
          1200,
          2000,
          2800
        ],
        "cols": 1,
        "aspect": "16 / 9",
        "alt": "Grampians Sandstone: Image Slider"
      },
      {
        "src": "images/grampians-sandstone/08-page-specifications",
        "widths": [
          1200,
          2400
        ],
        "cols": 3,
        "aspect": "4 / 5",
        "alt": "Grampians Sandstone: Page Specifications"
      },
      {
        "src": "images/grampians-sandstone/09-page-frame-2",
        "widths": [
          1200,
          2400
        ],
        "cols": 3,
        "aspect": "4 / 5",
        "alt": "Grampians Sandstone: Page Frame 2"
      },
      {
        "src": "images/grampians-sandstone/10-page-frame-3",
        "widths": [
          1200,
          2400
        ],
        "cols": 3,
        "aspect": "4 / 5",
        "alt": "Grampians Sandstone: Page Frame 3"
      },
      {
        "src": "images/grampians-sandstone/11-digger",
        "widths": [
          1200,
          2440
        ],
        "cols": 1,
        "aspect": "16 / 10",
        "alt": "Grampians Sandstone: Digger"
      },
      {
        "src": "images/grampians-sandstone/12-mobile-overlay",
        "widths": [
          1200,
          2000,
          2800
        ],
        "cols": 1,
        "aspect": "16 / 9",
        "alt": "Grampians Sandstone: Mobile Overlay"
      }
    ]
  },
  "courtside-wines": {
    "name": "Courtside Wines",
    "info": "Branding, Print & Web",
    "overview": "A personal concept project for a Hunter Valley estate winery aimed at a younger crowd. It covers a full brand rollout, from the identity and print pieces through to apparel, plus a simple storefront UI to bring it all together online.",
    "role": [
      "Brand Identity",
      "Print Design",
      "Apparel Design",
      "Website Design",
      "UI Design"
    ],
    "roleLabel": "",
    "team": [],
    "link": "",
    "linkLabel": "",
    "images": [
      {
        "src": "images/courtside-wines/01-tote",
        "widths": [
          1200,
          2880
        ],
        "cols": 1,
        "aspect": "16 / 10",
        "alt": "Courtside Wines: Tote"
      },
      {
        "src": "images/courtside-wines/02-vineyard-graphic",
        "widths": [
          1200,
          2000,
          2800
        ],
        "cols": 1,
        "aspect": "16 / 9",
        "alt": "Courtside Wines: Vineyard Graphic"
      },
      {
        "src": "images/courtside-wines/03-tshirt-front",
        "widths": [
          2309
        ],
        "cols": 2,
        "aspect": "2309 / 2880",
        "alt": "Courtside Wines: Tshirt Front"
      },
      {
        "src": "images/courtside-wines/04-tshirt-back",
        "widths": [
          2309
        ],
        "cols": 2,
        "aspect": "2309 / 2880",
        "alt": "Courtside Wines: Tshirt Back"
      },
      {
        "src": "images/courtside-wines/05-business-card",
        "widths": [
          1200,
          3000
        ],
        "cols": 1,
        "aspect": "16 / 9",
        "alt": "Courtside Wines: Business Card"
      },
      {
        "src": "images/courtside-wines/06-poster-01",
        "widths": [
          1188
        ],
        "cols": 3,
        "aspect": "1188 / 1680",
        "alt": "Courtside Wines: Poster 01"
      },
      {
        "src": "images/courtside-wines/07-poster-02",
        "widths": [
          1188
        ],
        "cols": 3,
        "aspect": "1188 / 1680",
        "alt": "Courtside Wines: Poster 02"
      },
      {
        "src": "images/courtside-wines/08-poster-03",
        "widths": [
          1188
        ],
        "cols": 3,
        "aspect": "1188 / 1680",
        "alt": "Courtside Wines: Poster 03"
      },
      {
        "src": "images/courtside-wines/09-multi-mag",
        "widths": [
          1200,
          2000,
          2800
        ],
        "cols": 1,
        "aspect": "16 / 10",
        "alt": "Courtside Wines: Multi Mag"
      },
      {
        "src": "images/courtside-wines/10-macbook-01",
        "widths": [
          1200,
          3000
        ],
        "cols": 1,
        "aspect": "16 / 10",
        "alt": "Courtside Wines: Macbook 01"
      },
      {
        "src": "images/courtside-wines/11-macbook-02",
        "widths": [
          1200,
          3000
        ],
        "cols": 1,
        "aspect": "16 / 10",
        "alt": "Courtside Wines: Macbook 02"
      }
    ]
  }
};
